/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as CoursesIntroToComputerGraphicsRouteImport } from './routes/courses/intro-to-computer-graphics'
import { Route as CoursesCapstoneRouteImport } from './routes/courses/capstone'
import { Route as CoursesCS493RouteImport } from './routes/courses/CS493'
import { Route as AboutMeServerManagementRouteImport } from './routes/about-me/server-management'
import { Route as AboutMeWorkExperienceItRouteImport } from './routes/about-me/work-experience/it'

const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIntroToComputerGraphicsRoute =
  CoursesIntroToComputerGraphicsRouteImport.update({
    id: '/intro-to-computer-graphics',
    path: '/intro-to-computer-graphics',
    getParentRoute: () => CoursesRoute,
  } as any)
const CoursesCapstoneRoute = CoursesCapstoneRouteImport.update({
  id: '/capstone',
  path: '/capstone',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCS493Route = CoursesCS493RouteImport.update({
  id: '/CS493',
  path: '/CS493',
  getParentRoute: () => CoursesRoute,
} as any)
const AboutMeServerManagementRoute = AboutMeServerManagementRouteImport.update({
  id: '/server-management',
  path: '/server-management',
  getParentRoute: () => AboutMeRoute,
} as any)
const AboutMeWorkExperienceItRoute = AboutMeWorkExperienceItRouteImport.update({
  id: '/work-experience/it',
  path: '/work-experience/it',
  getParentRoute: () => AboutMeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/about-me/server-management': typeof AboutMeServerManagementRoute
  '/courses/CS493': typeof CoursesCS493Route
  '/courses/capstone': typeof CoursesCapstoneRoute
  '/courses/intro-to-computer-graphics': typeof CoursesIntroToComputerGraphicsRoute
  '/demo/table': typeof DemoTableRoute
  '/about-me/work-experience/it': typeof AboutMeWorkExperienceItRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/about-me/server-management': typeof AboutMeServerManagementRoute
  '/courses/CS493': typeof CoursesCS493Route
  '/courses/capstone': typeof CoursesCapstoneRoute
  '/courses/intro-to-computer-graphics': typeof CoursesIntroToComputerGraphicsRoute
  '/demo/table': typeof DemoTableRoute
  '/about-me/work-experience/it': typeof AboutMeWorkExperienceItRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/about-me/server-management': typeof AboutMeServerManagementRoute
  '/courses/CS493': typeof CoursesCS493Route
  '/courses/capstone': typeof CoursesCapstoneRoute
  '/courses/intro-to-computer-graphics': typeof CoursesIntroToComputerGraphicsRoute
  '/demo/table': typeof DemoTableRoute
  '/about-me/work-experience/it': typeof AboutMeWorkExperienceItRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/courses'
    | '/about-me/server-management'
    | '/courses/CS493'
    | '/courses/capstone'
    | '/courses/intro-to-computer-graphics'
    | '/demo/table'
    | '/about-me/work-experience/it'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-me'
    | '/courses'
    | '/about-me/server-management'
    | '/courses/CS493'
    | '/courses/capstone'
    | '/courses/intro-to-computer-graphics'
    | '/demo/table'
    | '/about-me/work-experience/it'
  id:
    | '__root__'
    | '/'
    | '/about-me'
    | '/courses'
    | '/about-me/server-management'
    | '/courses/CS493'
    | '/courses/capstone'
    | '/courses/intro-to-computer-graphics'
    | '/demo/table'
    | '/about-me/work-experience/it'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRoute: typeof AboutMeRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  DemoTableRoute: typeof DemoTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/intro-to-computer-graphics': {
      id: '/courses/intro-to-computer-graphics'
      path: '/intro-to-computer-graphics'
      fullPath: '/courses/intro-to-computer-graphics'
      preLoaderRoute: typeof CoursesIntroToComputerGraphicsRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/capstone': {
      id: '/courses/capstone'
      path: '/capstone'
      fullPath: '/courses/capstone'
      preLoaderRoute: typeof CoursesCapstoneRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/CS493': {
      id: '/courses/CS493'
      path: '/CS493'
      fullPath: '/courses/CS493'
      preLoaderRoute: typeof CoursesCS493RouteImport
      parentRoute: typeof CoursesRoute
    }
    '/about-me/server-management': {
      id: '/about-me/server-management'
      path: '/server-management'
      fullPath: '/about-me/server-management'
      preLoaderRoute: typeof AboutMeServerManagementRouteImport
      parentRoute: typeof AboutMeRoute
    }
    '/about-me/work-experience/it': {
      id: '/about-me/work-experience/it'
      path: '/work-experience/it'
      fullPath: '/about-me/work-experience/it'
      preLoaderRoute: typeof AboutMeWorkExperienceItRouteImport
      parentRoute: typeof AboutMeRoute
    }
  }
}

interface AboutMeRouteChildren {
  AboutMeServerManagementRoute: typeof AboutMeServerManagementRoute
  AboutMeWorkExperienceItRoute: typeof AboutMeWorkExperienceItRoute
}

const AboutMeRouteChildren: AboutMeRouteChildren = {
  AboutMeServerManagementRoute: AboutMeServerManagementRoute,
  AboutMeWorkExperienceItRoute: AboutMeWorkExperienceItRoute,
}

const AboutMeRouteWithChildren =
  AboutMeRoute._addFileChildren(AboutMeRouteChildren)

interface CoursesRouteChildren {
  CoursesCS493Route: typeof CoursesCS493Route
  CoursesCapstoneRoute: typeof CoursesCapstoneRoute
  CoursesIntroToComputerGraphicsRoute: typeof CoursesIntroToComputerGraphicsRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCS493Route: CoursesCS493Route,
  CoursesCapstoneRoute: CoursesCapstoneRoute,
  CoursesIntroToComputerGraphicsRoute: CoursesIntroToComputerGraphicsRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRoute: AboutMeRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  DemoTableRoute: DemoTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
