/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTableRouteImport } from './routes/demo_/table'
import { Route as CoursesIntroToComputerGraphicsRouteImport } from './routes/courses_/intro-to-computer-graphics'
import { Route as CoursesCapstoneRouteImport } from './routes/courses_/capstone'
import { Route as CoursesCS493RouteImport } from './routes/courses_/CS493'
import { Route as AboutMeServerManagementRouteImport } from './routes/about-me_/server-management'
import { Route as AboutMeWorkExperienceItRouteImport } from './routes/about-me_/work-experience/it'

const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo_/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIntroToComputerGraphicsRoute =
  CoursesIntroToComputerGraphicsRouteImport.update({
    id: '/courses_/intro-to-computer-graphics',
    path: '/courses/intro-to-computer-graphics',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCapstoneRoute = CoursesCapstoneRouteImport.update({
  id: '/courses_/capstone',
  path: '/courses/capstone',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCS493Route = CoursesCS493RouteImport.update({
  id: '/courses_/CS493',
  path: '/courses/CS493',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeServerManagementRoute = AboutMeServerManagementRouteImport.update({
  id: '/about-me_/server-management',
  path: '/about-me/server-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeWorkExperienceItRoute = AboutMeWorkExperienceItRouteImport.update({
  id: '/about-me_/work-experience/it',
  path: '/about-me/work-experience/it',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/courses': typeof CoursesRoute
  '/about-me/server-management': typeof AboutMeServerManagementRoute
  '/courses/CS493': typeof CoursesCS493Route
  '/courses/capstone': typeof CoursesCapstoneRoute
  '/courses/intro-to-computer-graphics': typeof CoursesIntroToComputerGraphicsRoute
  '/demo/table': typeof DemoTableRoute
  '/about-me/work-experience/it': typeof AboutMeWorkExperienceItRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/courses': typeof CoursesRoute
  '/about-me/server-management': typeof AboutMeServerManagementRoute
  '/courses/CS493': typeof CoursesCS493Route
  '/courses/capstone': typeof CoursesCapstoneRoute
  '/courses/intro-to-computer-graphics': typeof CoursesIntroToComputerGraphicsRoute
  '/demo/table': typeof DemoTableRoute
  '/about-me/work-experience/it': typeof AboutMeWorkExperienceItRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/courses': typeof CoursesRoute
  '/about-me_/server-management': typeof AboutMeServerManagementRoute
  '/courses_/CS493': typeof CoursesCS493Route
  '/courses_/capstone': typeof CoursesCapstoneRoute
  '/courses_/intro-to-computer-graphics': typeof CoursesIntroToComputerGraphicsRoute
  '/demo_/table': typeof DemoTableRoute
  '/about-me_/work-experience/it': typeof AboutMeWorkExperienceItRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/courses'
    | '/about-me/server-management'
    | '/courses/CS493'
    | '/courses/capstone'
    | '/courses/intro-to-computer-graphics'
    | '/demo/table'
    | '/about-me/work-experience/it'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-me'
    | '/courses'
    | '/about-me/server-management'
    | '/courses/CS493'
    | '/courses/capstone'
    | '/courses/intro-to-computer-graphics'
    | '/demo/table'
    | '/about-me/work-experience/it'
  id:
    | '__root__'
    | '/'
    | '/about-me'
    | '/courses'
    | '/about-me_/server-management'
    | '/courses_/CS493'
    | '/courses_/capstone'
    | '/courses_/intro-to-computer-graphics'
    | '/demo_/table'
    | '/about-me_/work-experience/it'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRoute: typeof AboutMeRoute
  CoursesRoute: typeof CoursesRoute
  AboutMeServerManagementRoute: typeof AboutMeServerManagementRoute
  CoursesCS493Route: typeof CoursesCS493Route
  CoursesCapstoneRoute: typeof CoursesCapstoneRoute
  CoursesIntroToComputerGraphicsRoute: typeof CoursesIntroToComputerGraphicsRoute
  DemoTableRoute: typeof DemoTableRoute
  AboutMeWorkExperienceItRoute: typeof AboutMeWorkExperienceItRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/table': {
      id: '/demo_/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/intro-to-computer-graphics': {
      id: '/courses_/intro-to-computer-graphics'
      path: '/courses/intro-to-computer-graphics'
      fullPath: '/courses/intro-to-computer-graphics'
      preLoaderRoute: typeof CoursesIntroToComputerGraphicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/capstone': {
      id: '/courses_/capstone'
      path: '/courses/capstone'
      fullPath: '/courses/capstone'
      preLoaderRoute: typeof CoursesCapstoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/CS493': {
      id: '/courses_/CS493'
      path: '/courses/CS493'
      fullPath: '/courses/CS493'
      preLoaderRoute: typeof CoursesCS493RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me_/server-management': {
      id: '/about-me_/server-management'
      path: '/about-me/server-management'
      fullPath: '/about-me/server-management'
      preLoaderRoute: typeof AboutMeServerManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me_/work-experience/it': {
      id: '/about-me_/work-experience/it'
      path: '/about-me/work-experience/it'
      fullPath: '/about-me/work-experience/it'
      preLoaderRoute: typeof AboutMeWorkExperienceItRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRoute: AboutMeRoute,
  CoursesRoute: CoursesRoute,
  AboutMeServerManagementRoute: AboutMeServerManagementRoute,
  CoursesCS493Route: CoursesCS493Route,
  CoursesCapstoneRoute: CoursesCapstoneRoute,
  CoursesIntroToComputerGraphicsRoute: CoursesIntroToComputerGraphicsRoute,
  DemoTableRoute: DemoTableRoute,
  AboutMeWorkExperienceItRoute: AboutMeWorkExperienceItRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
